### ISSUE TITLE
Handle new-style "Web02" Clarity sites

### ISSUE THREAD

**Issue by dwillis** [openelections/clarify#35]
Like [West Virginia](http://results.enr.clarityelections.com/WV/74487/Web02-state.206999/#/), which clarify fails to parse and return any information from.

**Comment by migurski** [comment]
Is the example for Kentucky a new-style Clarity site? I’m seeing this error when following the README and curious if it’s part of this issue:

```Python
>>> import clarify
>>> j = clarify.Jurisdiction(url='http://results.enr.clarityelections.com/KY/15261/30235/en/summary.html', level='state')
>>> j.report_url('xml')
'https://results.enr.clarityelections.com/KY/15261/30235/reports/detailxml.zip'
>>> subs = j.get_subjurisdictions()
>>> subs[0].name
'Boone'
>>> subs[-1].report_url('xml')
'https://results.enr.clarityelections.com/KY/Woodford/15382/27566/reports/detailxml.zip'
```

(At this point I download and extract the Woodford XML to `/tmp/detail.xml`)

```Python
>>> p = clarify.Parser()
>>> p.parse("/tmp/detail.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/clarify/.venv/lib/python3.6/site-packages/clarify/parser.py", line 47, in parse
    self.voter_turnout = float(election_voter_turnout[2])
IndexError: list index out of range
```

**Comment by dwillis** [comment]
@migurski No, Kentucky is an older Clarity site, so this looks like a separate issue. Thanks for flagging it, though!

**Comment by migurski** [comment]
Ah cool — is there a current Clarity example that demonstrates working behavior?

**Comment by dwillis** [comment]
Just updated the README to use one.

**Comment by jonrobinson2** [comment]
Oh boo

**Comment by cjwinchester** [comment]
[Also Colorado](https://results.enr.clarityelections.com/CO/91808/Web02-state.220747/#/), if you need another test case.

**Comment by kyoung2112** [comment]
The new working README example is Georgia, which does use the new Clarity format. However, when I am browsing elections for Georgia, I don't see any result URLs in that format. How do you translate from the "Web02" style election result URL "http://results.enr.clarityelections.com/GA/91639/Web02-state.221451/#/" to the required format for summary.html "GA/xxxx/xxxx/en/summary.html" (where xxxx are the two numbers that need to be identified)?

**Comment by dwillis** [comment]
@kyoung2112 Thanks - we'll get that fixed on `j.report_url('xml')`

**Comment by bxjw** [comment]
It looks like there's now a new URL format that behaves pretty similarly to the WV and GA cases, but not exactly so it again breaks the code: https://results.enr.clarityelections.com/KY/103779/web.255599/#/reporting

**Comment by dwillis** [comment]
@bxjw Thanks - just pushed a fix for this but have not done a release yet. If you install directly from GitHub it should work.

**Comment by JDWarner** [comment]
@dwillis Most 2020 elections are now using the `web.XXXXXX` URL format, for example the GA 2020 general election here: https://results.enr.clarityelections.com/GA/105369/web.264614/#/summary

Installing from source current as of posting, neither this link nor the KY link posted previously work for `j.report_url('xml')` - it returns None - and both of those URLs hang in an infinite loop when requesting `get_subjurisdictions()`.
